
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.ctzbdwt4lwnj.ap-northeast-2.rds.amazonaws.com:3306/yeah24?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: dhkdwlgns98

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 500


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 981941917283-6vlebq33i2ftsmatudrhd15cso54ol56.apps.googleusercontent.com
            client-secret: dUw1CNDbEcI1s7gpAC_M40Rb
            scope:
              - email
              - profile

          naver:
            client-id: nv6FQu5gSDeBA06FewKp
            client-secret: qIyleloXUi
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키 값으로 네이버가 리턴해줌.

  servlet:
    multipart:
      enabled: true
      location: C:\Users\user\Desktop\no24\download
      max-request-size: 30MB
      max-file-size: 10MB